// kerjaan/selesai/cuti-msj/src/pages/data-ketua-divisi/edit/[id].svelte
<script>
  import departemen from "../../../yaml/departemen.yml";
  import jabatan from "../../../yaml/jabatan.yml";
  import level from "../../../yaml/level.yml";
  import seksi from "../../../yaml/seksi.yml";
  import stKel from "../../../yaml/st-kel.yml";
  import status from "../../../yaml/status.yml";
  import subDepartemen from "../../../yaml/sub-departemen.yml";
  import OptionKosong from "../../../komponen/option-kosong.svelte";
  import localforage from "localforage";
  import { push } from "svelte-spa-router";
  import toast from 'only-toast'

  export let params = {};

  let data = {
    nama: "",
    divisi: "",
  };

  async function ambilDatanya() {
    let semuaData = await localforage.getItem("data ketua divisi");
    semuaData = semuaData.filter((x) => x.id == params.id);
    data = semuaData[0];
  }
  ambilDatanya();

  let judul = 'Edit Data Ketua Divisi'

  document.title = judul;

  // Notification.requestPermission();

  async function simpan() {
    let semuaData = await localforage.getItem("data ketua divisi");
    semuaData = semuaData.filter((x) => x.id != params.id);
    semuaData = [...semuaData, data];
    const simpanYa = await localforage.setItem("data ketua divisi", semuaData);
    if (simpanYa) {
      // new Notification("Data tersimpan", {
      //   body: "Data ketua divisi berhasil disimpan",
      // });
      toast('Data tersimpan')
      push("/data-ketua-divisi");
    }
  }
</script>

<p class="uppercase text-lg mb-2 font-bold">{judul}</p>
<form action="" on:submit|preventDefault={simpan}>
  <div class="form grid grid-cols-2 gap-2">
    <div>
      <label for="">Nama</label>
      <input type="text" bind:value={data.nama} />
      
    </div>
    <div>
      <label for="">Departemen</label>
      <select name="" id="" bind:value={data.divisi}>
        <OptionKosong />
        {#each departemen as x}
          <option>{x}</option>
        {/each}
      </select>
    </div>
  </div>
  <div class="flex justify-end">
    <input
      type="submit"
      value="Simpan"
      class="mt-2 bg-black rounded p-2 border cursor-pointer text-white"
    />
  </div>
</form>

<style>
  :global(.form input),
  :global(.form select) {
    border: 1px solid var(--gray-300);
    width: 100%;
    padding: 0.25rem;
  }
</style>

// aplikasi-android/SUDAH-ADMOB/blog-new/lawas/app/src/main/assets/_src/pages/edit/[id].vue
<script setup="">
	import localforage from 'localforage'
	import {ref} from 'vue'
	import {useRouter, useRoute} from 'vue-router'

	const {push} = useRouter()
	const {params} = useRoute()

	const title = ref('')
	const content = ref('')

	async function getData(){
		let data = await localforage.getItem('dataBlog')
		data = data.filter(x => x.id == params.id)[0]
		title.value = data.title
		content.value = data.content
	}
	getData()

	async function save(){
		let data = await localforage.getItem('dataBlog')
		for (let x of data){
			if (x.id == params.id){
				x.title = title.value
				x.content = content.value
			}
		}
		let save = await localforage.setItem('dataBlog', data)
		if (save){
			push(`/read/${params.id}`)
		}
	}
</script>

<template>
	<form @submit.prevent='save' class="p-2" action="">
		<label for="">Title</label>
		<input v-model='title' type="text" required />
		<label for="">Content</label>
		<textarea v-model='content' name="" id="" cols="30" rows="10"></textarea>
		<input class="px-3 focus:outline-none cursor-pointer py-1 bg-green-500 rounded text-white" type="submit" value="Change" />
	</form>
</template>

<style scoped="">
	label {
		@apply font-bold mb-2 block
	}
	input:not([type=submit]), textarea {
		@apply focus:outline-none block border mb-2 p-2 w-full border-green-500/50 focus:border-green-500
	}
</style>
