// aplikasi-android/kumpulan-prompt-ai/src/pages/index.svelte
<script>
  import data from "../tiddlers/published.json";
  import { push } from "svelte-spa-router";
</script>

<div class="p-4">
  <div>
    <button
      class="btn mr-3"
      on:click={() =>
        (location.href =
          "https://play.google.com/store/apps/details?id=com.brainstorming.ai")}
      >Review App</button
    >
    <button
      class="btn"
      on:click={() =>
        (location.href =
          "https://play.google.com/store/apps/dev?id=5401138465689796048")}
      >Other Apps</button
    >
  </div>
  <div class="join mt-4 join-vertical">
    {#each data.sort((a, b) => (a.title > b.title ? 1 : -1)) as x}
      <button class="btn leading-[2] h-auto normal-case join-item"
        >{x.title}</button
      >
    {/each}
  </div>
</div>

// aplikasi-android/kartu-rencana/src/pages/index.vue
<script setup>
import { ref } from "vue";
import LinkTelegram from "../components/link-telegram.vue";

const data = ref([]);
if (localStorage.kartu_rencana) {
  data.value = JSON.parse(localStorage.kartu_rencana).sort((a, b) =>
    a.title > b.title ? 1 : -1
  );
}
</script>

<template>
  <div class="p-3">
    <div class="mb-3 kumpulan-tombol">
      <router-link :to="`/${Math.random()}`" class="btn btn-success"
        >Create</router-link
      >
      <router-link to="/semua-data" class="btn btn-success"
        >Semua Data</router-link
      >
    </div>
    <div class="list-group">
      <router-link
        :to="`/${x.id}`"
        v-for="x in data"
        class="list-group-item list-group-item-action"
        >{{ x.title }}
      </router-link>
    </div>

    <div class="mt-3 kumpulan-tombol">
      <a
        href="https://play.google.com/store/apps/details?id=com.chitandaeru.karturencana"
        class="btn btn-success"
        >Review App</a
      >
      <a
        href="https://play.google.com/store/apps/dev?id=5401138465689796048"
        class="btn btn-success"
        >Other Apps</a
      >
    </div>
    <!-- <LinkTelegram></LinkTelegram> -->
  </div>
</template>

<style scoped>
.kumpulan-tombol {
  display: flex;
  /* align-content: space-between; */
  /* flex-wrap: wrap; */
  justify-content: space-between;
}
</style>
